### ISSUE TITLE
切出去之后再切回来没有声音了

### ISSUE THREAD

**Issue by AndyGood** [susussa/VideoFeed#3]
作者君，你好啊。我体验了一下最新代码，切出去之后再切回来之后声音消失了，换下一个播放也是没有声音了。

**Comment by AndyGood** [comment]
好像也不会自动播放下一个视频了。全屏的时候也是。

**Comment by susussa** [comment]
@AndyGood 声音的问题已经解决了，这个问题，‘好像也不会自动播放下一个视频了。全屏的时候也是。’ 全屏的时候没有做自动播放下一个。
