### ISSUE TITLE
repeat video

### ISSUE THREAD

**Issue by chaolei-peng** [susussa/VideoFeed#5]
如果我想让单个视屏重播该怎么做了，发现在视屏播放完的回调中最后代码调用aoutPlayVideo()方法没有作用

**Comment by susussa** [comment]
1、自动重播：七牛的播放器自带的一个方法 setLoop() 循环播放。
2、可以在播放完成的回调里 加一个标记 重新赋 播放地址 也可以重新播。

现在代码的实现思想还是不完美，最近正在调整 -  思想重构，元旦之后会更新

**Comment by chaolei-peng** [comment]
感觉你思路可以的，在运行你这个项目中，我发现还有一个比较重要的问题，就是旋转之后重新下一个视屏无法播放，目测是播放器底层抛的错误：IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xd853fb80)
有可能是你在处理旋转之后移除或重新添加播放器调用错误，导致底层跑出异常；我尝试找写资料来看看那这是什么原因造成的，目前还没找到相对有价值的文档资料

**Comment by susussa** [comment]
https://www.jianshu.com/p/4db96418f32b  可以看下这个思路

**Comment by chaolei-peng** [comment]
谢谢，我参考一下
